// npm and Package Management
// Run with: npx tsx 02-npm.ts

console.log("=== npm and Package Management ===\n");

// ============================================
// LEVEL 1: Basics
// ============================================

console.log("=== LEVEL 1: Basics ===\n");

// package.json is the heart of every Node.js project
// It contains metadata about the project and its dependencies

// Example package.json structure (shown as object for learning)
const examplePackageJson = {
  name: "my-project",
  version: "1.0.0",
  description: "A sample project",
  main: "index.js",
  type: "module", // Important! Enables ES modules
  scripts: {
    start: "node index.js",
    dev: "nodemon index.js",
    test: "jest",
    build: "tsc",
  },
  keywords: ["node", "javascript"],
  author: "Your Name",
  license: "MIT",
};

console.log("Example package.json structure:");
console.log(examplePackageJson);

// ============================================
// LEVEL 2: Dependencies and Semantic Versioning
// ============================================

console.log("\n=== LEVEL 2: Dependencies ===\n");

// SEMANTIC VERSIONING (semver): MAJOR.MINOR.PATCH
// Example: 2.4.1
// - MAJOR (2): Breaking changes - upgrading might break your code
// - MINOR (4): New features - backward compatible
// - PATCH (1): Bug fixes - backward compatible

const versionExamples = {
  "1.0.0": "Initial release",
  "1.0.1": "Bug fix",
  "1.1.0": "New feature, still backward compatible",
  "2.0.0": "Breaking changes - may need code updates",
};

console.log("Semantic Versioning Examples:");
Object.entries(versionExamples).forEach(([version, meaning]) => {
  console.log(`  ${version}: ${meaning}`);
});

// DEPENDENCY TYPES
console.log("\nDependency Types:");

// 1. Regular dependencies (needed in production)
console.log("\n1. Regular dependencies (production):");
console.log("   Command: npm install <package>");
console.log("   Example: npm install express");
console.log("   Use for: Libraries needed to run your app");

// 2. Dev dependencies (only needed during development)
console.log("\n2. Dev dependencies (development only):");
console.log("   Command: npm install --save-dev <package>");
console.log("   Example: npm install --save-dev typescript");
console.log("   Use for: Testing, linting, building tools");

// Example packages
const productionDeps = ["express", "react", "lodash", "axios"];
const devDeps = ["typescript", "jest", "eslint", "prettier", "nodemon"];

console.log("\nProduction dependencies examples:", productionDeps.join(", "));
console.log("Dev dependencies examples:", devDeps.join(", "));

// VERSION RANGES in package.json
console.log("\nVersion Ranges:");
const versionRanges = {
  "^1.2.3": "Allows 1.x.x updates, but not 2.0.0 (most common)",
  "~1.2.3": "Allows patch updates only (1.2.x)",
  "1.2.3": "Exact version - no updates allowed",
  "*": "Any version (NOT recommended for production)",
  latest: "Always latest version (NOT recommended for production)",
};

Object.entries(versionRanges).forEach(([range, description]) => {
  console.log(`  "${range}": ${description}`);
});

// ============================================
// LEVEL 3: Scripts and package-lock.json
// ============================================

console.log("\n=== LEVEL 3: Scripts and Lock Files ===\n");

// NPM SCRIPTS
console.log("npm Scripts:");
console.log("  - Define shortcuts in package.json 'scripts' section");
console.log("  - Run with: npm run <script-name>");
console.log("  - Common scripts: start, dev, build, test, lint");

// Lifecycle scripts (special npm scripts)
const lifecycleScripts = {
  preinstall: "Runs before npm install",
  postinstall: "Runs after npm install",
  prestart: "Runs before npm start",
  poststart: "Runs after npm start",
  pretest: "Runs before npm test",
  posttest: "Runs after npm test",
};

console.log("\nLifecycle scripts (auto-run by npm):");
Object.entries(lifecycleScripts).forEach(([script, description]) => {
  console.log(`  ${script}: ${description}`);
});

// package-lock.json
console.log("\npackage-lock.json:");
console.log("  - Automatically generated by npm");
console.log("  - Locks exact versions of all dependencies");
console.log("  - Ensures reproducible installs across machines");
console.log("  - SHOULD be committed to git");

console.log("\nnpm install vs npm ci:");
console.log("  npm install:");
console.log("    - Reads package.json");
console.log("    - Updates package-lock.json if needed");
console.log("    - Good for local development");
console.log("  npm ci:");
console.log("    - ONLY reads package-lock.json");
console.log("    - Faster, cleaner install");
console.log("    - Deletes existing node_modules first");
console.log("    - Good for CI/CD pipelines");

// Other useful npm commands
console.log("\nUseful npm commands:");
const npmCommands = {
  "npm list": "Show installed packages",
  "npm list --depth=0": "Show top-level packages only",
  "npm outdated": "Check for updates",
  "npm update": "Update packages within version range",
  "npm audit": "Check for security vulnerabilities",
  "npm audit fix": "Fix security issues automatically",
  "npm uninstall <package>": "Remove a package",
  "npm info <package>": "Show package information",
};

Object.entries(npmCommands).forEach(([command, description]) => {
  console.log(`  ${command.padEnd(25)} ${description}`);
});

// ============================================
// Best Practices Summary
// ============================================

console.log("\n=== Best Practices ===");

console.log("\n✅ DO:");
console.log("  • Commit package-lock.json to version control");
console.log("  • Use ^ for most dependencies (allows safe updates)");
console.log("  • Separate production and dev dependencies");
console.log("  • Use npm scripts for common tasks");
console.log("  • Run npm audit regularly");
console.log("  • Use npm ci in CI/CD pipelines");
console.log("  • Keep dependencies updated but test before major upgrades");
console.log("  • Document why specific packages are needed");

console.log("\n❌ DON'T:");
console.log("  • Don't use * or latest in production");
console.log("  • Don't commit node_modules/");
console.log("  • Don't ignore package-lock.json");
console.log("  • Don't use npm install in production deployments");
console.log("  • Don't update major versions without testing");
console.log("  • Don't install unnecessary packages");

console.log("\n📦 Common Project Structure:");
console.log("  my-project/");
console.log("  ├── package.json");
console.log("  ├── package-lock.json  (commit this!)");
console.log("  ├── node_modules/      (don't commit)");
console.log("  └── src/");

console.log("\n✅ Practice complete!");
